### ISSUE TITLE
S24U

### ISSUE THREAD

**Issue by MajinOneTheOriginal** [Rem01Gaming/encore#3]
Sadly not work on S24 Ultra, have force reboots

**Comment by Rem01Gaming** [comment]
When random reboots usually happen?

**Comment by MajinOneTheOriginal** [comment]
After boot, 10-20 seconds after it has booted, can I help somehow so that you can find the problem, do you need data from build.prop or something?

**Comment by Rem01Gaming** [comment]
You can try running encore-perfcommon, encore-performance, encore-normal, and encore-powersave manually on shell (don't install the module) and tell with script caused random reboot

**Comment by MajinOneTheOriginal** [comment]
strange if I run everything as a shell there is no force reboot, there is a lot in termux, but I don't understand much of it, hmm if only I could help with a log

**Comment by Rem01Gaming** [comment]
Weird

**Comment by Rem01Gaming** [comment]
> strange if I run everything as a shell there is no force reboot, there is a lot in termux, but I don't understand much of it, hmm if only I could help with a log

Have you run it with root permission?

**Comment by MajinOneTheOriginal** [comment]
I will try again

**Comment by MajinOneTheOriginal** [comment]
I don't think it worked with termux, then I tried the fx file explorer, added the file extensions with .sh and tried to run it with root but I get error messages, otherwise I'll try the mpatcher from apktool

**Comment by MajinOneTheOriginal** [comment]
I just tried the mpatcher and got this error message with powersave, don't know if you can do anything with it 

cat: /data/encore/soc_recognition: No such file or directory
/data/user/0/ru.maximoff.sheller/files/scripts/1724929760572_9451.sh[117]: [: 1: unexpected operator/operand
/data/user/0/ru.maximoff.sheller/files/scripts/1724929760572_9451.sh[117]: [: 2: unexpected operator/operand
/data/user/0/ru.maximoff.sheller/files/scripts/1724929760572_9451.sh[117]: [: 4: unexpected operator/operand

**Comment by Rem01Gaming** [comment]
Try this build, someone have identical issue with you and was fixed with this build.
https://github.com/Rem01Gaming/encore/actions/runs/10615345693

**Comment by MajinOneTheOriginal** [comment]
I've now tried the build with v1.2, I really wanted it to work, but unfortunately it still force reboot

**Comment by MajinOneTheOriginal** [comment]
EncoreTweaks 1.4 works like a charm for S24U
Thanks a lot

**Comment by MajinOneTheOriginal** [comment]
Works now
